services:
  - type: web
    name: customer-churn-prediction
    env: python
    region: oregon  # or choose a region closer to your users
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true